### ISSUE TITLE
Vault Unsealing

### ISSUE THREAD

**Issue by aarondglover** [MrZoidberg/VaultSharp.Extensions.Configuration#5]
### Automatic Vault Unsealing

Just before I was about to embark on writing my own Configuration Provider I found this project. Thank you for sharing!!!

This project is JUST what I was looking for before however I would wish to extend on it ever so slightly with the **OPTIONAL** ability for the library to Unseal the Vault if it is currently sealed.

I know the recommended usage of VAULT is that Initializing and Unsealing should be done by some administrator user, but I find very useful - particularly during development, to have my code unseal the vault which is required typically after each stop/start of the vault.exe.

How would you feel about the ability to provide a `List<string>` of unseal keys to the `VaultConfigurationOptions` and if the unseal keys are provided the Configuration Provider will check the seal status and if it is sealed, then unseal it.

Thanks in Advance

**Comment by MrZoidberg** [comment]
Hi,

Thanks for your proposal. I really do think that init and unseal cannot be a part of .NET Configuration and there are good reasons for this:

- First of all, during initialization and unseal procedure Vault gives you several unseal tokens that should be saved securely to be used to unseal/seal Vault. Also, the root token is generated. This library cannot save these info in some secure place because the only secure place it has is just Vault itself and you would lose access to all secrets once Vault is sealed or you forget the root token.
- Usually, the permissions that are given to the Vault client that is using Vault to read secrets are very limited. In my practice, every app has read-only access to only it's part of the KV storage and cannot do init and unseal procedures.
- For local or dev setup you can [run Vault in dev mode](https://www.vaultproject.io/docs/concepts/dev-server) that doesn't need initializing or unsealing and you can define some root token.

Please let me know if you still have some problems with your dev setup and I will try to help you.

**Comment by aarondglover** [comment]
I understand not wanting to put this into the solution.. I cloned the project and made the changes in my solution.

FWIW, in Dev rather than using it in dev mode I am storing the unseal key and root token in UserSecrets.

In production I envisage making these docker environment variables which are restricted to a single microservice for whom one of its responsibilities will be to monitor the vault container and also to ensure it is unsealed.
